services:
    nginx:
        image: nginx:latest
        working_dir: /var/www/html
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./public:/var/www/html
        depends_on:
            - php

    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        working_dir: /var/www/html
        volumes:
            - ./public:/var/www/html
        
    mysql:
        image: mariadb:latest
        working_dir: /var/www/html
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: test
            MYSQL_USER: Ninjamari
            MYSQL_PASSWORD: password
        volumes:
            - .:/var/www/html
        ports:
            - 3306:3306

    database:
        image: adminer:latest
        ports:
            - 8080:8080